DROP TABLE IF EXISTS T_MYCATALOG;

CREATE TABLE T_MYCATALOG(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    FLOW_ID VARCHAR(50) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    CODE VARCHAR(20) NOT NULL,
    PARENT_ID VARCHAR(50) NOT NULL,
    USE_PATTERN VARCHAR(20) NOT NULL,
    NUM INT(11) NULL DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8;

CREATE TABLE LH_MY_CODE_STANDARD(
    CODE_STANDARD_ID INT(11) NOT NULL AUTO_INCREMENT,
    FLOW_ID VARCHAR(50) NOT NULL,
    CN_NAME VARCHAR(20) NOT NULL,
    CODE_NAME VARCHAR(20) NOT NULL,
    CODE_RULE VARCHAR(20),
    USE_COUNT VARCHAR(20),
    DESCRIPTION VARCHAR(200),
    CATALOG_ID VARCHAR(50) NOT NULL,
    PART_COUNT INT(11) NOT NULL,
    EFFECTIVE_STATE VARCHAR(20) DEFAULT 'draft',
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'pending',
    PRIMARY KEY (CODE_STANDARD_ID)
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8;

CREATE TABLE LH_MY_CODE_STANDARD_PART(
	CODE_STANDARD_PART_ID INT(11) NOT NULL AUTO_INCREMENT,
	PARENT_ID VARCHAR(50) NOT NULL,
	PART_TYPE VARCHAR(20) NOT NULL,
	PART_NAME VARCHAR(20) NOT NULL,
	PART_LENGTH INT(6),
	SEGMENT_CHAR INT(50),
	CONSTANT VARCHAR(50),
	LETTER_NUM_COMBINE VARCHAR(6),
	START_VALUE VARCHAR(6),
	END_VALUE VARCHAR(6),
	PRIMARY KEY (CODE_STANDARD_PART_ID)
) ENGINE = INNODB AUTO_INCREMENT = 1 CHARACTER SET = UTF8;

